#!/bin/bash

# This function is used by bash completion to display all options for a specific action

options() {

  _help

  for PARAM in "${!_PARAM[@]}"; do printf -- "--%s " "${PARAM}"; done
  for PARAM_FLAG in "${!_PARAM_FLAG[@]}"; do printf -- "--%s " "${PARAM_FLAG}"; done
}
