#!/bin/bash

help_modules() {

  printf "Usage : furnace (MODULE) (ACTION) [PARAMETERS]\nAvailable modules :\n"
  printf -- "%s\n" "$(find "${INSTALL_DIR}"/bin/ -name "*" | awk -F - '{print $2}' | sort | uniq | tr '\n' ' ')"
}

help_actions() {

  printf "Usage : furnace %s (ACTION) [PARAMETERS]\nAvailable actions :\n" "${1}"
  printf -- "%s\n" "$(find "${INSTALL_DIR}"/bin/ -name "${1}-*" | awk -F - '{print $3}' | sort | uniq | tr '\n' ' ')"
}

options() {

  _help

  for PARAM in "${!_PARAM[@]}"; do printf -- "--%s" "${PARAM}"; done
  for PARAM_FLAG in "${!_PARAM_FLAG[@]}"; do printf -- "--%s" "${PARAM_FLAG}"; done
}