#!/bin/bash

# The functions in this file take care of the cases when the user passes the --help argument

help_modules() {

  printf "Usage : furnace (MODULE) (ACTION) [PARAMETERS]\nAvailable modules :\n"
  printf -- "%s\n" "$(find "${INSTALL_DIR}"/bin/ "${INSTALL_DIR}"/modules/ -mindepth 1 -name "*" -printf "%f\n" | awk -F - '{print $1}' | sort | uniq | tr '\n' ' ')"
}

help_actions() {

  printf "Usage : furnace %s (ACTION) [PARAMETERS]\nAvailable actions :\n" "${1}"
  printf -- "%s\n" "$(find "${INSTALL_DIR}"/bin/ -name "${1}-*" | awk -F - '{print $3}' | sort | uniq | tr '\n' ' ')"
}

help() {

  _help

  printf "Usage : furnace %s %s %s\nDescription : %s\nOptions :\n" "${_MODULE}" "${_ACTION}" "${_USAGE}" "${_DESCRIPTION}"
  printf -- "%s" "$(for PARAM in "${!_PARAM[@]}"; do echo "--${PARAM}, -${_PARAM[$PARAM]} | ${_HELP[$PARAM]}\n"; done)$(for PARAM_FLAG in "${!_PARAM_FLAG[@]}"; do echo "--${PARAM_FLAG}, -${_PARAM_FLAG[$PARAM_FLAG]} | ${_HELP[$PARAM_FLAG]}\n"; done)
	" | column -t -s'|'
}